s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Arduino kartına bağlanıldı. İyi eğlenceler!',
    'An error was detected on the board\n\n': 'HATA! Arduino kartı üzerinde hata bulundu.\n\n',
    'Board is not connected': 'Arduino kartı bağlı değil.',
    'Board was disconnected from port\n': 'Port bağlantısı kesildi port\n',
    'Check if firmata is loaded.': 'Frimata nın yüklü oldup olmadığını kontrol edin.',
    'Connect Arduino': 'Seri Porta Bağlan',
    'Connecting board at port\n': 'Arduino kartına bağlanıyor port\n ',
    'Could not connect an Arduino\nNo boards found': 'Aruino ya bağlanılamadı\nKart bulunamadı.',
    'Could not talk to Arduino in port\n': 'Arduino ile iletişim kurulamadı port\n',
    'Disconnect Arduino': 'Bağlantıyı Kes',
    'Error connecting the board.': 'HATA! Arduino ya bağlanırken hata oluştu.',
    'It seems that someone pulled the cable!': 'HATA! Bağlantı kablosunu kontrol edin!',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Bu karakter zaten bir Arduino ya bağlı.',
    'analog reading _': 'Analog pin oku A _',
    'angle (0-180)': 'Açı (0-180)',
    'clockwise (1500-1000)': 'Saat Yönü (1500-1000)',
    'clockwise': 'Saat Yönü',
    'connect arduino at _': 'Ardunio ya bağlan port: _',
    'connect to Arduino': 'Arduino ya bağlan',
    'counter-clockwise (1500-2000)': 'Saat Yönünün Tersi (1500-2000)',
    'counter-clockwise': 'Saat Yönünün Tersi',
    'digital input': 'Sayısal Giriş',
    'digital output': 'Sayısal Çıkış',
    'digital reading _': 'Sayısal pin oku D _',
    'disconnect Arduino': 'Arduino Bağlantısını Kes',
    'disconnect arduino': 'Ardunio bağlantısını kes',
    'servo': 'Servo',
    'set digital pin _ to _': 'Sayısal pin D _ değerini _ yap',
    'set pin _ to value _': 'Sayısal pin D _ değerini _ yap',
    'set servo _ to _': 'Servo pin D _ değerini _ yap',
    'setup digital pin _ as _': 'Sayısal pin D _ durumunu _ yap',
    'stopped (1500)': 'Durduruldu (1500)',
    'stopped': 'Durduruldu'
};
for (var attrname in s4aTempDict) { SnapTranslator.dict.tr[attrname] = s4aTempDict[attrname]; }
