s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Arduino zostało podłączone. Miłego prototypowania!',
    'An error was detected on the board\n\n': 'Wykryto błąd na płytce\n\n',
    'Board is not connected': 'Płytka nie jest podłączona',
    'Board was disconnected from port\n': 'Płytka została odłączona od portu\n',
    'Check if firmata is loaded.': 'Sprawdź, czy Firmata jest wgrana.',
    'Connect Arduino': 'Połącz z Arduino',
    'Connecting board at port\n': 'Łączenie z płytką na porcie\n',
    'Connecting to network port:\n': 'Łączenie z portem sieciowym:\n',
    'Could not connect an Arduino\nNo boards found': 'Nie udało się połączyć z Arduino\nNie znaleziono płytki',
    'Could not talk to Arduino in port\n': 'Brak komunikacji z Arduino na porcie\n',
    'Disconnect Arduino': 'Odłącz Arduino',
    'Enter hostname or ip address:': 'Wpisz nazwę hosta lub adres ip:',
    'Error connecting the board.': 'Błąd w trakcie podłączania do płytki.',
    'It seems that someone pulled the cable!': 'Wygląda na to że ktoś odłączył kabel!',
    'Network port': 'Port sieciowy',
    'Network serial ports': 'Sieciowe porty szeregowe',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Jest już płytka podłączona do tego duszka',
    'This may take a few seconds...': 'To może potrwać kilka sekund...',
    'analog reading _': 'odczyt analogowy _',
    'angle (0-180)': 'kąt (0-180)',
    'arduino connected?': 'Arduino podłączone?',
    'clockwise (1500-1000)': 'zgodnie z ruchem wskazówek (1500-1000)',
    'clockwise': 'zgodnie z ruchem wskazówek',
    'connect arduino at _': 'połącz z Arduino przez port _',
    'connect to Arduino': 'połącz z Arduino',
    'counter-clockwise (1500-2000)': 'przeciwnie do ruchu wskazówek (1500-2000)',
    'counter-clockwise': 'przeciwnie do ruchu wskazówek',
    'digital input': 'wejście cyfrowe',
    'digital output': 'wyjście cyfrowe',
    'digital reading _': 'odczyt cyfrowy _',
    'disconnect Arduino': 'odłącz Arduino',
    'disconnect arduino': 'odłącz Arduino',
    'disconnected': 'odłączony',
    'select a port': 'wybierz port',
    'servo': 'serwo',
    'set digital pin _ to _': 'ustaw cyfrowy pin _ na _',
    'set pin _ to value _': 'ustaw PWM pin _ na _',
    'set servo _ to _': 'ustaw serwo _ na _',
    'setup digital pin _ as _': 'ustal cyfrowy pin _ jako _',
    'stopped (1500)': 'zatrzymany (1500)',
    'stopped': 'zatrzymany'
};
// Add attributes to original SnapTranslator.dict.pl
for (var attrname in s4aTempDict) { SnapTranslator.dict.pl[attrname] = s4aTempDict[attrname]; }
