s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Arduino plaat on ühendatud. Jõudu tööle!',
    'An error was detected on the board\n\n': 'Viga plaadil\n\n',
    'Board is not connected': 'Plaat pole ühendatud',
    'Board was disconnected from port\n': 'Plaat eemaldati pordist\n',
    'Check if firmata is loaded.': 'Veendu, et firmata oleks laaditud.',
    'Connect Arduino': 'Ühenda Arduino',
    'Connecting board at port\n': 'Ühenduse loomine plaadiga pordis\n',
    'Could not connect an Arduino\nNo boards found': 'Arduinoga ei saadud ühendust.\nPlaate ei leitud.',
    'Could not talk to Arduino in port\n': 'Arduinoga suhtlemine ei õnnestu pordis\n',
    'Disconnect Arduino': 'Katkesta ühendus Arduinoga',
    'Error connecting the board.': 'Viga plaadiga ühenduse loomisel.',
    'It seems that someone pulled the cable!': 'Paistab, et keegi tõmbas kaabli välja.',
    'New Arduino translatable project': 'Uus tõlgitav Arduino projekt',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Selle spraidiga on juba plaat seotud.',
    'analog reading _': 'analooglugem viigult _',
    'angle (0-180)': 'nurk (0-180)',
    'clockwise (1500-1000)': 'päripäeva (1500-1000)',
    'clockwise': 'päripäeva',
    'connect arduino at _': 'tekita ühendus arduinoga pordis _',
    'connect to Arduino': 'ühenda Arduino',
    'counter-clockwise (1500-2000)': 'vastupäeva (1500-2000)',
    'counter-clockwise': 'vastupäeva',
    'digital input': 'digitaalne sisend',
    'digital output': 'digitaalne väljund',
    'digital reading _': 'digitaallugem viigult _',
    'disconnect Arduino': 'katkesta ühendus Arduinoga',
    'disconnect arduino': 'katkesta ühendus arduinoga',
    'disconnected': 'ühendus katkestatud',
    'servo': 'servo',
    'set digital pin _ to _': 'määra digitaalviigule _ väärtus _',
    'set pin _ to value _': 'määra viigule _ väärtus _',
    'set servo _ to _': 'määra servoviigule _ väärtus _',
    'setup digital pin _ as _': 'määra digitaalviigu _ režiimiks _',
    'stopped (1500)': 'peatatud (1500)',
    'stopped': 'peatatud'
};
// Add attributes to original SnapTranslator.dict.et
for (var attrname in s4aTempDict) { SnapTranslator.dict.et[attrname] = s4aTempDict[attrname]; }
