s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Deska Arduino byla připojena. Veselé prototypování!',
    'An error was detected on the board\n\n': 'Detekována chyba na desce\n\n',
    'Board is not connected': 'Deska není připojena',
    'Board was disconnected from port\n': 'Deska byla odpojena od portu\n',
    'Check if firmata is loaded.': 'Zkontrolujte, zda je na desce nahrána Firmata.',
    'Connect Arduino': 'Připojit Arduino',
    'Connecting board at port\n': 'Připojuji desku na port\n',
    'Could not connect an Arduino\nNo boards found': 'Nezdařilo se připojení k Arduinu\nNenalezena žádná deska',
    'Could not talk to Arduino in port\n': 'Komunikace s Arduinem se nedaří na portu\n',
    'Disconnect Arduino': 'Odpojit Arduino',
    'Error connecting the board.': 'Chyba při připojení k desce.',
    'It seems that someone pulled the cable!': 'Zdá se, že někdo vytáhl kabel!',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'K tomuto sprite je již deska připojena',
    'analog reading _': 'analogový vstup _',
    'angle (0-180)': 'úhel (0-180)',
    'clockwise (1500-1000)': 'po směru hodin (1500-1000)',
    'clockwise': 'po směru hodin',
    'connect arduino at _': 'připojit Arduino na portu _',
    'connect to Arduino': 'připojit Arduino',
    'counter-clockwise (1500-2000)': 'proti směru hodin (1500-2000)',
    'counter-clockwise': 'proti směru hodin',
    'digital input': 'digitální vstup',
    'digital output': 'digitální výstup',
    'digital reading _': 'digitální vstup _',
    'disconnect Arduino': 'odpojit Arduino',
    'disconnect arduino': 'odpojit Arduino',
    'servo': 'servo',
    'set digital pin _ to _': 'nastav digitální pin _ na _',
    'set pin _ to value _': 'nastav PWM pin _ na _',
    'set servo _ to _': 'nastav servo _ na _',
    'setup digital pin _ as _': 'nastav digitální pin _ jako _',
    'stopped (1500)': 'zastaveno (1500)',
    'stopped': 'zastaveno'
};
// Add attributes to original SnapTranslator.dict.cs
for (var attrname in s4aTempDict) { SnapTranslator.dict.cs[attrname] = s4aTempDict[attrname]; }
