s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'La carte Arduino a \u00E9t\u00E9 connect\u00E9e. Bon prototypage !',
    'An error was detected on the board\n\n': 'Une erreur a \u00E9t\u00E9 d\u00E9tect\u00E9e sur la carte\n\n',
    'Board is not connected': 'La carte n\'est pas connect\u00E9',
    'Board was disconnected from port\n': 'La carte a \u00E9t\u00E9 d\u00E9connect\u00E9e du port\n',
    'Check if firmata is loaded.': 'V\u00E9rifier que firmata est charg\u00E9.',
    'Connect Arduino': 'Connecter Arduino',
    'Connecting board at port\n': 'Connexion de la carte au port\n',
    'Could not connect an Arduino\nNo boards found': 'Impossible de se connecter \u00E0 Arduino\nAucune carte trouv\u00E9e',
    'Could not talk to Arduino in port\n': 'Impossible de communiquer avec Arduino sur le port\n',
    'Disconnect Arduino': 'D\u00E9connecter Arduino',
    'Error connecting the board.': 'Erreur de connexion \u00E0 la carte',
    'It seems that someone pulled the cable!': 'Il semble que quelqu\'un ait arrach\u00E9 le cable !',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Il y a d\u00E9j\u00E0 une carte connect\u00E9e \u00E0 ce lutin',
    'analog reading _': 'lecture analogique _',
    'angle (0-180)': 'angle (0-180)',
    'clockwise (1500-1000)': 'sens horaire (1500-1000)',
    'clockwise': 'sens horaire',
    'connect arduino at _': 'connecte arduino au port _',
    'connect to Arduino': 'connect\u00E9 \u00E0 Arduino',
    'counter-clockwise (1500-2000)': 'sens anti-horaire (1500-2000)',
    'counter-clockwise': 'sens anti-horaire',
    'digital input': 'entr\u00E9e num\u00E9rique',
    'digital output': 'sortie num\u00E9rique',
    'digital reading _': 'lecture num\u00E9rique _',
    'disconnect Arduino': 'd\u00E9connect\u00E9 \u00E0 Arduino',
    'disconnect arduino': 'd\u00E9connecte arduino',
    'servo': 'servo',
    'set digital pin _ to _': 'mettre la pin num\u00E9rique _ \u00E0 _',
    'set pin _ to value _': 'mettre la pin _ \u00E0 _',
    'set servo _ to _': 'mettre le servo _ \u00E0 _',
    'setup digital pin _ as _': 'mettre la pin num\u00E9rique _ en _',
    'stopped (1500)': 'arr\u00E9t (1500)',
    'stopped': 'arr\u00E9t'
};
// Add attributes to original SnapTranslator.dict.fr
for (var attrname in s4aTempDict) { SnapTranslator.dict.fr[attrname] = s4aTempDict[attrname]; }
