s4aTempDict = {
    'About Snap4Arduino...': 'Snap4Arduino-ri buruz...',
    'An Arduino board has been connected. Happy prototyping!': 'Arduino plaka bat konektatu da.\nPrototipatze zoriontsua!',
    'An error was detected on the board\n\n': 'Errore bat detektatu da plakan\n\n',
    'Board is not connected': 'Plaka ez dago konektatuta',
    'Board was disconnected from port\n': 'Plaka atakatik deskonektatu da\n',
    'Check if firmata is loaded.': 'Egiaztatu firmata kargatuta dagoen.',
    'Connect Arduino': 'Konektatu Arduinoa',
    'Connecting board at port\n': 'Plaka atakan konektatzen\n',
    'Connecting to network port:\n': 'Sareko atakara konektatzen:\n',
    'Could not connect an Arduino\nNo boards found': 'Ezin izan da Arduinoa konektatu\nEz da plakarik aurkitu',
    'Could not talk to Arduino in port\n': 'Ezin izan da atakako Arduinoarekin komunikatu\n',
    'Disconnect Arduino': 'Deskonektatu Arduinoa',
    'Enter hostname or ip address:': 'Sartu ostalari-izena edo IP helbidea:',
    'Error connecting the board.': 'Errorea plaka konektatzean.',
    'It seems that someone pulled the cable!': 'Norbaitek kablea atera duela dirudi!',
    'Loading Snap Jr.': 'Snap Jr. kargatzen',
    'Network port': 'Sareko ataka',
    'Network serial ports': 'Sareko serieko atakak',
    'New Arduino translatable project': 'Arduino proiektu itzulgarri berria',
    'Open from URL...': 'Ireki URLtik...',
    'PWM': 'PWM',
    'Save, share and get URL...': 'Gorde, partekatu eta eskuratu URLa...',
    'Snap4Arduino repository': 'Snap4Arduino biltegia',
    'Snap4Arduino website': 'Snap4Arduino webgunea',
    'Start Snap4Arduino in an\nicon-based blocks mode\nfor the youngest programmers': 'Hasi Snap4Arduino\nikonoetan oinarritutako bloke moduan\nprogramatzaile gazteenentzat',
    'Start a Snap Jr. session': 'Hasi Snap Jr. saioa',
    'There is already a board connected to this sprite': 'Dagoeneko plaka bat dago objektu honetara konektatuta',
    'This may take a few seconds...': 'Honek segundo batzuk beharko ditu...',
    'This project is now public at the following URL:': 'Proiektu hau publikoki eskuragarri dago ondorengo URLan:',
    'analog reading _': 'irakurketa analogikoa _ pinean',
    'angle (0-180)': 'angelua (0-180)',
    'arduino connected?': 'arduinoa konektatuta?',
    'clockwise (1500-1000)': 'erlojuaren noranzkoan (1500-1000)',
    'clockwise': 'erlojuaren noranzkoan',
    'connect arduino at _': 'konektatu arduinoa _ atakan',
    'connect to Arduino': 'konektatu Arduinoa',
    'counter-clockwise (1500-2000)': 'erlojuaren aurkako noranzkoan (1500-2000)',
    'counter-clockwise': 'erlojuaren aurkako noranzkoan',
    'digital input': 'sarrera digitala',
    'digital output': 'irteera digitala',
    'digital reading _': 'irakurketa digitala _ pinean',
    'disconnect Arduino': 'deskonektatu Arduinoa',
    'disconnect arduino': 'deskonektatu arduinoa',
    'disconnected': 'deskonektatuta',
    'select a port': 'hautatu ataka',
    'servo': 'serbomotorra',
    'set digital pin _ to _': 'ezarri _ pin digitalean _ balioa',
    'set pin _ to value _': 'ezarri _ pinean _ balioa',
    'set servo _ to _': 'ezarri _ serbomotorra _ bezala',
    'setup digital pin _ as _': 'konfiguratu _ pin digitala _ bezala',
    'stopped (1500)': 'geldituta (1500)',
    'stopped': 'geldituta'
};
// Add attributes to original SnapTranslator.dict.eu
for (var attrname in s4aTempDict) { SnapTranslator.dict.eu[attrname] = s4aTempDict[attrname]; }
