s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Target telah terhubung. Selamat berkarya!',
    'An error was detected on the board\n\n': 'Ditemukan adanya kesalahan pada target\n\n',
    'Board is not connected': 'Target tidak terhubung',
    'Board was disconnected from port\n': 'Target telah terlepas dari port\n',
    'Check if firmata is loaded.': 'Periksalah apakah firmata telah terpasang.',
    'Connect Arduino': 'Hubungkan Arduino',
    'Connecting board at port\n': 'Menghubungkan target pada port\n',
    'Connecting to network port:\n': 'Menghubungkan ke port jaringan:\n',
    'Could not connect an Arduino\nNo boards found': 'Tidak dapat terhubung dengan Arduino\nTarget tidak ditemukan',
    'Could not talk to Arduino in port\n': 'Tidak dapat terhubung dengan Arduino pada port\n',
    'Disconnect Arduino': 'Lepaskan hubungan Arduino',
    'Enter hostname or ip address:': 'masukkan nama host atau alamat ip:',
    'Error connecting the board.': 'Terjadi kesalahan saat menghubungkan target',
    'It seems that someone pulled the cable!': 'Sepertinya ada yang mencabut kabelnya!',
    'Network port': 'Port jaringan',
    'Network serial ports': 'Port serial jaringan',
    'New Arduino translatable project': 'Buat proyek yang dapat dikonversi ke Arduino',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Sudah ada target yang terhubung ke sprite ini',
    'This may take a few seconds...': 'Ini mungkin membutuhkan beberapa detik...',
    'analog reading _': 'pembacaan analog _',
    'angle (0-180)': 'sudut (0-180)',
    'clockwise (1500-1000)': 'searah jarum jam (1500-1000)',
    'clockwise': 'searah jarum jam',
    'connect arduino at _': 'hubungkan arduino ke port _',
    'connect to Arduino': 'hubungkan dengan Arduino',
    'counter-clockwise (1500-2000)': 'berlawanan jarum jam (1500-2000)',
    'counter-clockwise': 'berlawanan jarum jam',
    'digital input': 'masukan digital',
    'digital output': 'keluaran digital',
    'digital reading _': 'pembacaan digital _',
    'disconnect Arduino': 'lepaskan hubungan dengan Arduino',
    'disconnect arduino': 'lepaskan hubungan dengan arduino',
    'select a port': 'pilih port',
    'servo': 'servo',
    'set digital pin _ to _': 'set pin digital _ menjadi _',
    'set pin _ to value _': 'set pin _ menjadi bernilai _',
    'set servo _ to _': 'set servo _ menjadi _',
    'setup digital pin _ as _': 'atur pin digital _ sebagai _',
    'stopped (1500)': 'berhenti (1500)',
    'stopped': 'berhenti'
};
// Add attributes to original SnapTranslator.dict.id
for (var attrname in s4aTempDict) { SnapTranslator.dict.id[attrname] = s4aTempDict[attrname]; }
