s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Вдале з\u2019єднання з платою Arduino.\nЦікавих експериментів!',
    'An error was detected on the board\n\n': 'З цією платою виникли проблеми\n\n',
    'Board is not connected': 'Плату від\u2019єднано',
    'Board was disconnected from port\n': 'Плату було від\u2019єднано від порту\n',
    'Check if firmata is loaded.': 'Перевірити, чи завантажено скетч Firmata.',
    'Connect Arduino': 'З\u2019єднатися з Arduino',
    'Connecting board at port\n': 'З\u2019єднання з платою через порт\n',
    'Could not connect an Arduino\nNo boards found': 'Неможлио з\u2019єднатися з Arduino\nНе знайдено жодної плати',
    'Could not talk to Arduino in port\n': 'Помилка обміну даними з Arduino через порт\n',
    'Disconnect Arduino': 'Від\u2019єднатися від Arduino',
    'Error connecting the board.': 'Неможило з\u2019єднатися з платою.',
    'It seems that someone pulled the cable!': 'Можливо, USB кабель було від\u2019єднано!',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'З цим спрайтом вже існує з\u2019єднання',
    'analog reading _': 'аналогове значення _',
    'angle (0-180)': 'кут (0-180)',
    'arduino connected?': 'arduino під\u2019єднано?',
    'clockwise (1500-1000)': 'за годинниковою стрілкою (1500-1000)',
    'clockwise': 'за годинниковою стрілкою',
    'connect arduino at _': 'з\u2019єднатися з arduino використовуючи _',
    'connect to Arduino': 'з\u2019єднатися з Arduino',
    'counter-clockwise (1500-2000)': 'проти годинникової стрілки (1500-2000)',
    'counter-clockwise': 'проти годинникової стрілки',
    'digital input': 'цифровий вхід',
    'digital output': 'цифровий вихід',
    'digital reading _': 'цифрове значення _',
    'disconnect Arduino': 'від\u2019єднатися від Arduino',
    'disconnect arduino': 'від\u2019єднатися від arduino',
    'servo': 'серво',
    'set digital pin _ to _': 'встановити цифровий пін _ як _',
    'set pin _ to value _': 'встановити пін PWM _ як _',
    'set servo _ to _': 'встановити пін серво _ як _',
    'setup digital pin _ as _': 'налаштувати цифровий пін _ як _',
    'stopped (1500)': 'зупинено (1500)',
    'stopped': 'зупинено'
};
// Add attributes to original SnapTranslator.dict.ua
for (var attrname in s4aTempDict) { SnapTranslator.dict.ua[attrname] = s4aTempDict[attrname]; }
