s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': '接上Arduino板了，祝你玩得愉快！',
    'An error was detected on the board\n\n': '在控制板上發現錯誤\n\n',
    'Board is not connected': '沒有連接控制板',
    'Board was disconnected from port\n': '控制板已中斷連線了，通訊埠：\n',
    'Check if firmata is loaded.': '檢查是否已經載入Firmata韌體。',
    'Connect Arduino': '連接到Arduino板',
    'Connecting board at port\n': '正在連接控制板，通訊埠：\n',
    'Connecting to network port:\n': '連線到網路通訊埠：\n',
    'Could not connect an Arduino\nNo boards found': '無法連接到Arduino\n找不到控制板',
    'Could not talk to Arduino in port\n': '無法與Arduino聯繫，通訊埠：\n',
    'Disconnect Arduino': '斷開與Arduino的連接',
    'Enter hostname or ip address:': '輸入主機名稱或IP位址：',
    'Error connecting the board.': '連接控制板時發生錯誤',
    'It seems that someone pulled the cable!': '看來有人拔掉連接線了！',
    'Network port': '網路通訊埠',
    'Network serial ports': '網路序列埠',
    'New Arduino translatable project': '新增Arduino可轉譯專案',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': '已經有一個控制板連接到這個角色了',
    'This may take a few seconds...': '可能要等數秒…',
    'analog reading _': '類比輸入值 _',
    'angle (0-180)': '角度 (0-180)',
    'clockwise (1500-1000)': '順時針 (1500-1000)',
    'clockwise': '順時針',
    'connect arduino at _': '連接位於 _ 的Arduino板',
    'connect to Arduino': '連接到Arduino板',
    'counter-clockwise (1500-2000)': '逆時針 (1500-2000)',
    'counter-clockwise': '逆時針',
    'digital input': '數位輸入',
    'digital output': '數位輸出',
    'digital reading _': '數位輸入值 _',
    'disconnect Arduino': '斷開與Arduino的連接',
    'disconnect arduino': '斷開與Arduino的連接',
    'disconnected': '斷開連接',
    'select a port': '選擇一個通訊埠',
    'servo': '伺服馬達',
    'set digital pin _ to _': '數位腳 _ 設定成 _',
    'set pin _ to value _': '_ 腳的值設定成 _',
    'set servo _ to _': '_ 腳的伺服馬達設定成 _',
    'setup digital pin _ as _': '數位腳 _ 設置成 _',
    'stopped (1500)': '停止 (1500)',
    'stopped': '停止'
};
// Add attributes to original SnapTranslator.dict.zh_TW
for (var attrname in s4aTempDict) { SnapTranslator.dict.zh_TW[attrname] = s4aTempDict[attrname]; }
