s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'La scheda Arduino \u00E8 correttamente collegata.\nBuona sperimentazione!',
    'An error was detected on the board\n\n    ': 'Un errore \u00E8 stato riscontrato sulla scheda\n\n',
    'Board is not connected    ': 'La scheda non \u00E8 collegata',
    'Board was disconnected from port\n    ': 'La scheda \u00E8 stata scollegata dalla porta\n',
    'Check if firmata is loaded.    ': 'Verifica che Firmata sia caricato sulla scheda.',
    'Connect Arduino    ': 'Collega Arduino',
    'Connecting board at port\n': 'Sto collegando la scheda alla porta\n',
    'Could not connect an Arduino\nNo boards found    ': 'Impossibile collegarsi ad Arduino\nNessuna scheda trovata',
    'Could not talk to Arduino in port\n    ': 'Impossibile comunicare con Arduino alla porta\n',
    'Disconnect Arduino    ': 'Scollega Arduino',
    'Error connecting the board.    ': 'Errore di connessione alla scheda',
    'It seems that someone pulled the cable!    ': 'Sembra che qualcuno ha staccato il cavo!',
    'PWM    ': 'PWM',
    'There is already a board connected to this sprite    ': 'C\'\u00E8 gi\u00E0 una scheda collegata a questo oggetto',
    'analog reading _    ': 'lettura analogica _',
    'angle (0-180)    ': 'angolo (0-180)',
    'clockwise    ': 'senso orario',
    'clockwise (1500-1000)    ': 'senso orario (1500-1000)',
    'connect arduino at _    ': 'collega arduino alla porta _',
    'connect to Arduino    ': 'collegati ad Arduino',
    'counter-clockwise    ': 'senso anti-orario',
    'counter-clockwise (1500-2000)    ': 'senso anti-orario (1500-2000)',
    'digital input    ': 'ingresso digitale',
    'digital output    ': 'uscita digitale',
    'digital reading _    ': 'lettura digitale _',
    'disconnect Arduino    ': 'scollega Arduino',
    'disconnect arduino    ': 'scollega arduino',
    'servo    ': 'servo',
    'set digital pin _ to _    ': 'imposta il pin digitale _ a _',
    'set pin _ to value _    ': 'imposta il pin _ a _',
    'set servo _ to _    ': 'imposta servo _ a _',
    'setup digital pin _ as _    ': 'imposta il pin _ come _',
    'stopped    ': 'fermo',
    'stopped (1500)    ': 'fermo (1500)'
};
// Add attributes to original SnapTranslator.dict.it
for (var attrname in s4aTempDict) { SnapTranslator.dict.it[attrname] = s4aTempDict[attrname]; }
