s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Um Arduino foi conectado.\nFeliz prototipagem!',
    'An error was detected on the board\n\n': 'Foi detectado um erro na placa\n\n',
    'Board is not connected': 'O Arduino não está conectado',
    'Board was disconnected from port\n': 'A placa foi desconectada da porta\n',
    'Check if firmata is loaded.': 'Verifique se Firmata foi gravado no Arduino',
    'Connect Arduino': 'Conectar Arduino',
    'Connecting board at port\n': 'Conectando o Arduino na porta\n',
    'Could not connect an Arduino\nNo boards found': 'Não consegui conectar a um Arduino\nNão encontrei nenhuma placa',
    'Could not talk to Arduino in port\n': 'Não consegui comunicar com Arduino na porta\n',
    'Disconnect Arduino': 'Desconectar Arduino',
    'Error connecting the board.': 'Erro ao conectar ao Arduino',
    'It seems that someone pulled the cable!': 'Parece que alguém desconectou o cabo!',
    'New Arduino translatable project': 'Novo projeto tradutível para Arduino',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Já há um Arduino conectado e este ator',
    'analog reading _': 'o valor analógico no pino _',
    'angle (0-180)': 'com ângulo (0-180)',
    'clockwise (1500-1000)': 'no sentido horário (1500-1000)',
    'clockwise': 'no sentido horário',
    'connect arduino at _': 'conecte Arduino em _',
    'connect to Arduino': 'conectar ao Arduino',
    'counter-clockwise (1500-2000)': 'no sentido anti-horário (1500-2000)',
    'counter-clockwise': 'no sentido anti-horário',
    'digital input': 'entrada digital',
    'digital output': 'saída digital',
    'digital reading _': 'o valor booleano no pino digital _ é «verdadeiro»',
    'disconnect Arduino': 'desconectar do Arduino',
    'disconnect arduino': 'desconecte Arduino',
    'disconnected': 'desligado',
    'servo': 'servo',
    'set digital pin _ to _': 'coloque no pino digital _ o valor booleano _',
    'set pin _ to value _': 'coloque no pino _ o valor _',
    'set servo _ to _': 'posicione o servo _ em _',
    'setup digital pin _ as _': 'configure o pino digital _ como _',
    'stopped (1500)': 'parado (1500)',
    'stopped': 'parado'
};
// Add attributes to original SnapTranslator.dict.pt_BR
for (var attrname in s4aTempDict) { SnapTranslator.dict.pt_BR[attrname] = s4aTempDict[attrname]; }
