s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Uma placa Arduino foi ligada.\nFeliz prototipagem!',
    'An error was detected on the board\n\n': 'Detectou-se um erro na placa\n\n',
    'Board is not connected': 'A placa não está ligada',
    'Board was disconnected from port\n': 'A placa foi desligada do porto\n',
    'Check if firmata is loaded.': 'Verifique se a firmata já foi carregada.',
    'Connect Arduino': 'Ligar Arduino',
    'Connecting board at port\n': 'Ligando placa no porto\n',
    'Could not connect an Arduino\nNo boards found': 'Não foi possível ligar a um Arduino\nNão foram encontradas placas',
    'Could not talk to Arduino in port\n': 'Não foi possível comunicar com o Arduino no porto\n',
    'Disconnect Arduino': 'Desligar Arduino',
    'Error connecting the board.': 'Erro ao ligar à placa',
    'It seems that someone pulled the cable!': 'Parece que alguém desligou o cabo!',
    'New Arduino translatable project': 'Novo projecto traduzível para Arduino',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Este objecto já tem uma placa ligada',
    'analog reading _': 'o valor analógico no pino _',
    'angle (0-180)': 'com ângulo (0-180)',
    'clockwise (1500-1000)': 'no sentido dos ponteiros do relógio (1500-1000)',
    'clockwise': 'no sentido dos ponteiros do relógio',
    'connect arduino at _': 'liga ao Arduino em _',
    'connect to Arduino': 'ligar ao Arduino',
    'counter-clockwise (1500-2000)': 'no sentido contrário aos ponteiros do relógio (1500-2000)',
    'counter-clockwise': 'no sentido contrário aos ponteiros do relógio',
    'digital input': 'entrada digital',
    'digital output': 'saída digital',
    'digital reading _': 'o valor booleano no pino digital _ é «verdadeiro»',
    'disconnect Arduino': 'desligar do Arduino',
    'disconnect arduino': 'desliga do Arduino',
    'disconnected': 'desligado',
    'servo': 'servo',
    'set digital pin _ to _': 'coloca no pino digital _ o valor booleano _',
    'set pin _ to value _': 'coloca no pino (PWM) _ o valor _',
    'set servo _ to _': 'coloca o servo _ _',
    'setup digital pin _ as _': 'configura o pino digital _ como _',
    'stopped (1500)': 'parado (1500)',
    'stopped': 'parado'
};
// Add attributes to original SnapTranslator.dict.pt
for (var attrname in s4aTempDict) { SnapTranslator.dict.pt[attrname] = s4aTempDict[attrname]; }
