#!/bin/sh
# Just some utility function to colorfully print stuff

print_ok() {
   echo "\033[32m$1\033[0m" 
}

print_warning() {
   echo "\033[30;43mWARNING:\033[0;33m $1\033[0m" 
}

print_error() {
    (>&2 echo "\033[37;41mERROR:\033[0m \033[1;31m$1\033[0m");
}
