s4aTempDict = {
    'About Snap4Arduino...': 'Sobre Snap4Arduino...',
    'An Arduino board has been connected. Happy prototyping!': 'Conectouse satisfactoriamente unha tarxeta Arduino.\nFeliz prototipaxe!',
    'An error was detected on the board\n\n': 'Detectouse un erro na tarxeta\n\n',
    'Blocks for TdRSTEAM shield v1, using SA5Firmata firmware.': 'Bloques para a TdRSTEAM v1, empregado o SA5Firmata.',
    'Blocks for TdRSTEAM shield v2, using SA5Firmata firmware.': 'Bloques para a TdRSTEAM v2, empregando o SA5Firmata.',
    'Board is not connected': 'A tarxeta non está conectada',
    'Board was disconnected from port\n': 'Desconectouse a tarxeta do porto\n',
    'Check if firmata is loaded.': 'Verifique se o firmware Firmata foi cargado.',
    'Connect Arduino': 'Conectar Arduino',
    'Connecting board at port\n': 'Conectando tarxeta no porto\n',
    'Connecting to network port:\n': 'Conectando ao porto de rede:\n',
    'Could not connect an Arduino\nNo boards found': 'Non se puido conectar un Arduino\nNon se atopou ningunha tarxeta',
    'Could not talk to Arduino in port\n': 'Non se puido comunicar con Arduino no porto\n',
    'Disconnect Arduino': 'Desconectar Arduino',
    'End of Snap4Arduino libraries.': 'Final das bibliotecas do Snap4Arduino.',
    'Enter hostname or ip address:': 'Introduza o nome da máquina ou o seu enderezo IP',
    'Error connecting the board.': 'Produciuse un erro ao conectar a tarxeta',
    'Extra blocks for SnapJunior.': 'Bloques para engadir funcionalidades ao Snap Junior',
    'HTTP server': 'Servidor HTTP',
    'Icon-based blocks for the youngest programmers.': 'Bloques con iconas para os programadores e programadoras máis novos/as.',
    'It seems that someone pulled the cable!': 'Parece que alguén desconectou o cable!',
    'Libraries below this point are specific to Snap4Arduino.': 'As bibliotecas baixo este punto son específicas para Snap4Arduino.',
    'Loading Snap Jr.': 'Snap Junior está a cargarse',
    'Network port': 'Porto de rede',
    'Network serial ports': 'Portos serie sobre rede',
    'New Arduino translatable project': 'Novo proxecto traducible a Arduino',
    'Open from URL...': 'Abrir dende un URL...',
    'PWM': 'PWM',
    'Public stage': 'Escenario público',
    'Save, share and get URL...': 'Garda, comparte e amosa o URL...',
    'Snap4Arduino repository': 'Repositoro do Snap4Arduino',
    'Snap4Arduino website': 'Web do Snap4Arduino',
    'SnapJunior Blocks': 'Bloques do Snap Junior',
    'SnapJuniorPlus Blocks': 'Máis bloques para o Snap Junior',
    'Start Snap4Arduino in an\nicon-based blocks mode\nfor the youngest programmers': 'Inicia Snap4Arduino nun\nmodo de bloques con iconas\npara os/as programadores/as máis novos/as',
    'Start a Snap Jr. session': 'Iniciar unha sesión de Snap Junior',
    'There is already a board connected to this sprite': 'Xa existe unha tarxeta conectada a este obxecto',
    'This may take a few seconds...': 'isto pode levar uns segundos...',
    'This project is now public at the following URL:': 'Este proxecto é público, accesíbel dende o URL:',
    'analog reading _': 'lectura analóxica _',
    'angle (0-180)': 'ángulo (0-180)',
    'arduino connected?': 'Arduino está conectado?',
    'blue': 'azul',
    'check to allow the stage\nto be viewed\nfrom the HTTP server': 'márqueo para permitir que o escenario\nsexa visto dende o servidor HTTP',
    'check to start\nHTTP server, allowing\nremote control\nof Snap4Arduino': 'márqueo para iniciar\no servidor HTTP, permitindo\no control remoto\nde Snap4Arduino',
    'clockwise (1500-1000)': 'sentido horario (1500-1000)',
    'clockwise': 'sentido horario',
    'connect arduino at _': 'conectar Arduino ao porto _',
    'connect to Arduino': 'conectar a Arduino',
    'counter-clockwise (1500-2000)': 'sentido anti-horario (1500-2000)',
    'counter-clockwise': 'sentido anti-horario',
    'digital input': 'entrada dixital',
    'digital output': 'saída dixital',
    'digital reading _': 'lectura dixital _',
    'disconnect Arduino': 'desconectar Arduino',
    'disconnect arduino': 'desconectar Arduino',
    'disconnected': 'desconectado',
    'red': 'vermello',
    'select a port': 'seleccione un porto',
    'servo': 'servo',
    'set digital pin _ to _': 'fixar pin dixital _ en _',
    'set pin _ to value _': 'fixar pin _ ao valor _',
    'set servo _ to _': 'fixar servo _ en _',
    'setup digital pin _ as _': 'configurar pin _ como _',
    'stopped (1500)': 'parado (1500)',
    'stopped': 'parado',
    'uncheck to prevent the stage\nfrom being viewed\nfrom the HTTP server': 'desmarqueo para evitar que o escenario\nsexa visto dende o servidor HTTP',
    'uncheck to stop\nHTTP server': 'desmarque para deter\no servidor HTTP'
};
// Add attributes to original SnapTranslator.dict.gl
for (var attrname in s4aTempDict) { SnapTranslator.dict.gl[attrname] = s4aTempDict[attrname]; }
