s4aTempDict = {
    'About Snap4Arduino...': 'Sobre Snap4Arduino...',
    'An Arduino board has been connected. Happy prototyping!': 'Se conectó exitosamente una tarjeta Arduino.\n¡Feliz prototipado!',
    'An error was detected on the board\n\n': 'Se detectó un error en la tarjeta\n\n',
    'Board is not connected': 'La tarjeta no está conectada',
    'Board was disconnected from port\n': 'Se deconectó la tarjeta de la puerta\n',
    'Check if firmata is loaded.': 'Revise si tiene cargado el firmware Firmata.',
    'Connect Arduino': 'Conectar Arduino',
    'Connecting board at port\n': 'Conectando tarjeta en la puerta\n',
    'Connecting to network port:\n': 'Conectando a puerta de red:\n',
    'Could not connect an Arduino\nNo boards found': 'No se pudo conectar un Arduino\nNo se encontró ninguna tarjeta',
    'Could not talk to Arduino in port\n': 'No se pudo comunicar con Arduino en la puerta\n',
    'Disconnect Arduino': 'Desconectar Arduino',
    'Enter hostname or ip address:': 'Introduzca el nombre del host o su dirección IP',
    'Error connecting the board.': 'Error al conectar la tarjeta',
    'HTTP server': 'Servidor HTTP',
    'It seems that someone pulled the cable!': '¡Parece que alguien desconectó el cable!',
    'More supported devices': 'Otros dispositivos compatibles',
    'Network port': 'Puerta de red',
    'Network serial ports': 'Puertas serie sobre red',
    'New Arduino translatable project': 'Nuevo proyecto traducible a Arduino',
    'Open from URL...': 'Abre desde una URL...',
    'PWM': 'PWM',
    'Public stage': 'Escenario público',
    'Save, share and get URL...': 'Guarda, comparte y muestra la URL...',
    'Snap4Arduino connector required': 'Conector de Snap4Arduino requerido',
    'Snap4Arduino repository': 'Repositorio de Snap4Arduino',
    'Snap4Arduino website': 'Web de Snap4Arduino',
    'Start a Snap Jr. session': 'Inicia una sesión de Snap Junior',
    'There is already a board connected to this sprite': 'Ya existe una tarjeta conectada a este objeto',
    'This may take a few seconds...': 'Esto puede tardar unos segundos...',
    'This project is now public at the following URL:': 'Este proyecto es público, accessible desde la URL:',
    'Upload firmware on UNO boards': 'Actualitzar el firmware de placas UNO',
    'analog reading _': 'lectura analógica _',
    'angle (0-180)': 'ángulo (0-180)',
    'arduino connected?': '¿arduino connectado?',
    'check to allow the stage\nto be viewed\nfrom the HTTP server': 'marcar para permitir que el escenario\nse visualice desde el servidor HTTP',
    'check to start\nHTTP server, allowing\nremote control\nof Snap4Arduino': 'marcar para iniciar\nel servidor HTTP, habilitando\nel control remoto\nde Snap4Arduino',
    'clockwise (1500-1000)': 'sentido horario (1500-1000)',
    'clockwise': 'sentido horario',
    'connect arduino at _': 'conectar arduino al puerto _',
    'connect to Arduino': 'conectar a Arduino',
    'counter-clockwise (1500-2000)': 'sentido anti-horario (1500-2000)',
    'counter-clockwise': 'sentido anti-horario',
    'digital input': 'entrada digital',
    'digital output': 'salida digital',
    'digital reading _': 'lectura digital _',
    'disconnect Arduino': 'desconectar Arduino',
    'disconnect arduino': 'desconectar arduino',
    'disconnected': 'desconectado',
    'select a port': 'seleccione una puerta',
    'servo': 'servo',
    'set digital pin _ to _': 'fijar pin digital _ en _',
    'set pin _ to value _': 'fijar pin _ al valor _',
    'set servo _ to _': 'fijar servo _ en _',
    'setup digital pin _ as _': 'configurar pin _ como _',
    'stopped (1500)': 'parado (1500)',
    'stopped': 'parado',
    'uncheck to prevent the stage\nfrom being viewed\nfrom the HTTP server': 'desmarcar para evitar que el escenario\nse visualice desde el servidor HTTP',
    'uncheck to stop\nHTTP server': 'desmarcar para detener\nel servidor HTTP'
};
// Add attributes to original SnapTranslator.dict.es
for (var attrname in s4aTempDict) { SnapTranslator.dict.es[attrname] = s4aTempDict[attrname]; }
