s4aTempDict = {
    'About Snap4Arduino...': 'Sobre Snap4Arduino...',
    'Adding extra features to StandardFirmata: tone, pulseIn, pulseOut, ping, nunchuck and dht11 blocks. It requires SA5Firmata_tone firmware.': 'Añade funcionalidades al StandardFirmata: tone, pulseIn, pulseOut, ping, nunchuck i dht11. Necesita que el dispositivo tenga el firmware SA5Firmata_tone.',
    'An Arduino board has been connected. Happy prototyping!': 'Se conectó exitosamente una tarjeta Arduino.\n¡Feliz prototipeo!',
    'An error was detected on the board\n\n': 'Se detectó un error en la tarjeta\n\n',
    'Blocks for the Echidna boards. Use StandarFirmata or SA5Firmata_tone to add more buzzer features.': 'Bloques para las placas Echidna. Utiliza el StandardFirmata o el SA5Firmata_tone para añadir las funcionalidades del zumbador (tone).',
    'Blocks for the Imagina shield. Use StandardFirmata, SA5Firmata_tone to add buzzer features or SA5Firmata_IR for buzzer and IR features.': 'Bloques para la placa Imagina. Utiliza el StandardFirmata, el S5AFirmata_tone para añadir las funcionalidades del zumbador (tone) o el SA5Firmata_IR para tener zumbador (simplificado) y funcionalidades IR.',
    'Blocks for the NodeMCU board using StandardFirmata. It has also blocks for a motor shield.': 'Bloques para la placa NodeMCU utilitzando el StandardFirmata. También incorpora bloques para la placa de motores.',
    'Blocks for the TdRSTEAM shield v1. Use StandardFirmata or SA5Firmata_tone firmware to add buzzer features.': 'Bloques para la TdRSTEAM v1. Utiliza el StandardFirmata o el SA5Firmata_tone para añadir las funcionalidades del zumbador (tone).',
    'Blocks for the TdRSTEAM shield v2, Use StandardFirmata or SA5Firmata_tone firmware to add buzzer features.': 'Bloques para la TdRSTEAM v2. Utiliza el StandardFirmata o el SA5Firmata_tone para añadir las funcionalidades del zumbador (tone).',
    'Board is not connected': 'La tarjeta no está conectada',
    'Board was disconnected from port\n': 'Se deconectó la tarjeta de la puerta\n',
    'Check if firmata is loaded.': 'Revise si tiene cargado el firmware Firmata.',
    'Connect Arduino': 'Conectar Arduino',
    'Connecting board at port\n': 'Conectando tarjeta en la puerta\n',
    'Connecting to network port:\n': 'Conectando a puerta de red:\n',
    'Could not connect an Arduino\nNo boards found': 'No se pudo conectar un Arduino\nNo se encontró ninguna tarjeta',
    'Could not talk to Arduino in port\n': 'No se pudo comunicar con Arduino en la puerta\n',
    'Disconnect Arduino': 'Desconectar Arduino',
    'Echidna Boards': 'Placas Echidna',
    'Enter hostname or ip address:': 'Introduzca el nombre del host o su dirección IP',
    'Error connecting the board.': 'Error al conectar la tarjeta',
    'Extra blocks for SnapJunior.': 'Bloques para añadir funcionalidades al Snap Junior',
    'HTTP server': 'Servidor HTTP',
    'I2C': 'I2C',
    'Icon-based blocks for the youngest programmers.': 'Bloques con iconos para los programadores y programadoras más jóvenes.',
    'Imagina Shield': 'Placa Imagina',
    'It seems that someone pulled the cable!': '¡Parece que alguien desconectó el cable!',
    'Libraries below this point are specific to Snap4Arduino.': 'Las siguientes bibliotecas son específicas de Snap4Arduino.',
    'More supported devices': 'Otros dispositivos compatibles',
    'Network port': 'Puerta de red',
    'Network serial ports': 'Puertas serie sobre red',
    'New Arduino translatable project': 'Nuevo proyecto traducible a Arduino',
    'Open from URL...': 'Abre desde una URL...',
    'PWM': 'PWM',
    'Public stage': 'Escenario público',
    'SA5Firmata with IR features at the expense of simplifying the tone function. It requires SA5Firmata_ir firmware.': 'SA5Firmata con funcionalidades IR, limitando las funcionalidades del tone. Necesita que el dispositivo tinga el firmware SA5Firmata_IR.',
    'Save, share and get URL...': 'Guarda, comparte y muestra la URL...',
    'Scale a value from a range to another. Useful to map sensor values into stage coordinates, or to map sensors into actuators.': 'Escala un valor de un intervalo a otro. Útil para mapear valores de sensores a las coordenadas del escenario o para pasar directamente valores de sensores a actuadores.',
    'Scale between ranges': 'Escala entre intervalos',
    'Send and receive data from I2C-enabled sensors and actuators.': 'Envía y recibe datos por el protocolo I2C de sensores y actuadores.',
    'Snap4Arduino connector required': 'Conector de Snap4Arduino requerido',
    'Snap4Arduino repository': 'Repositorio de Snap4Arduino',
    'Snap4Arduino website': 'Web de Snap4Arduino',
    'SnapJunior Blocks': 'Bloques del Snap Junior',
    'SnapJuniorPlus Blocks': 'Más bloques para el Snap Junior',
    'Start a Snap Jr. session': 'Inicia una sesión de Snap Junior',
    'There is already a board connected to this sprite': 'Ya existe una tarjeta conectada a este objeto',
    'This may take a few seconds...': 'Esto puede tardar unos segundos...',
    'This project is now public at the following URL:': 'Este proyecto es público, accessible desde la URL:',
    'Upload firmware on UNO boards': 'Actualitzar el firmware de placas UNO',
    'analog reading _': 'lectura analógica _',
    'angle (0-180)': 'ángulo (0-180)',
    'arduino connected?': '¿arduino connectado?',
    'check to allow the stage\nto be viewed\nfrom the HTTP server': 'marcar para permitir que el escenario\nse visualice desde el servidor HTTP',
    'check to start\nHTTP server, allowing\nremote control\nof Snap4Arduino': 'marcar para iniciar\nel servidor HTTP, habilitando\nel control remoto\nde Snap4Arduino',
    'clockwise (1500-1000)': 'sentido horario (1500-1000)',
    'clockwise': 'sentido horario',
    'connect arduino at _': 'conectar arduino al puerto _',
    'connect to Arduino': 'conectar a Arduino',
    'counter-clockwise (1500-2000)': 'sentido anti-horario (1500-2000)',
    'counter-clockwise': 'sentido anti-horario',
    'digital input': 'entrada digital',
    'digital output': 'salida digital',
    'digital reading _': 'lectura digital _',
    'disconnect Arduino': 'desconectar Arduino',
    'disconnect arduino': 'desconectar arduino',
    'disconnected': 'desconectado',
    'select a port': 'seleccione una puerta',
    'servo': 'servo',
    'set digital pin _ to _': 'fijar pin digital _ en _',
    'set pin _ to value _': 'fijar pin _ al valor _',
    'set servo _ to _': 'fijar servo _ en _',
    'setup digital pin _ as _': 'configurar pin _ como _',
    'stopped (1500)': 'parado (1500)',
    'stopped': 'parado',
    'uncheck to prevent the stage\nfrom being viewed\nfrom the HTTP server': 'desmarcar para evitar que el escenario\nse visualice desde el servidor HTTP',
    'uncheck to stop\nHTTP server': 'desmarcar para detener\nel servidor HTTP'
};
// Add attributes to original SnapTranslator.dict.es
for (var attrname in s4aTempDict) { SnapTranslator.dict.es[attrname] = s4aTempDict[attrname]; }
