s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'ארדוינו חובר  בהצלחה!',
    'An error was detected on the board\n\n':  'אותרה שגיאה בארדוינו\n\n' ,
    'Arduino':'ארדוינו' ,
    'Board is not connected': 'הארדוינו לא מחובר',
    'Board was disconnected from port\n': 'המעגל נותק\n',
    'Check if firmata is loaded.':   'נא בדוק שפירמטה טעון בארדוינו' ,
    'Connect Arduino': 'התחבר לארדוינו',
    'Connecting board at port\n':  'חבר לכניסה\n',
    'Could not connect an Arduino\nNo boards found': 'לא נמצא ארדוינו לחבר',
    'Could not talk to Arduino in port\n':  'לא ניתן לתקשר עם הארדוינו\n',
    'Disconnect Arduino':  'התנתק מהארדוינו',
    'Error connecting the board.': 'שגיאה בחיבור' ,
    'It seems that someone pulled the cable!':  'נראה שמישהו ניתק את הכבל!',
    'PWM': 'מנוע' ,
    'There is already a board connected to this sprite': 'יש ארדוינו שכבר מחובר לספרייט הזה' ,
    'analog reading _': '_ מ אנלוגית קריאה',
    'angle (0-180)': '(זווית (0-180',
    'clockwise (1500-1000)': '(1500-1000) השעון כוון עם' ,
    'clockwise': 'השעון כוון עם' ,
    'connect arduino at _': '_ לפורט ארדוינו חבר',
    'connect to Arduino': 'התחבר לארדוינו',
    'counter-clockwise (1500-2000)': '(1500-2000) השעון כוון נגד',
    'counter-clockwise': 'השעון כוון נגד',
    'digital input':'כניסה דיגיטלית' ,
    'digital output': 'יציאה דיגיטלית' ,
    'digital reading _': '_ מ ספרתית קריאה' ,
    'disconnect Arduino':  'התנתק מהארדוינו',
    'disconnect arduino':  'התנתק מהארדוינו',
    'servo': 'סרבו',
    'set digital pin _ to _':  '_ -ל _ דיגיטליית רגל שנה',
    'set pin _ to value _': '_ -ל _ ברגל PWM קבע',
    'set servo _ to _': '_ -ל _ ברגל מנוע הבא',
    'setup digital pin _ as _':  '_ -ב _  רגל קבע',
    'stopped (1500)': '(1500) עצור',
    'stopped': 'עצור'
};
// Add attributes to original SnapTranslator.dict.he
for (var attrname in s4aTempDict) { SnapTranslator.dict.he[attrname] = s4aTempDict[attrname]; }
