s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': '接上Arduino板了，祝你玩得愉快！',
    'An error was detected on the board\n\n': '在控制板上发现错误\n\n',
    'Board is not connected': '没有连接控制板',
    'Board was disconnected from port\n': '控制板已中断连接，端口：\n',
    'Check if firmata is loaded.': '检查是否已经加载Firmata固件。',
    'Connect Arduino': '连接到Arduino板',
    'Connecting board at port\n': '正在连接控制板，端口：\n',
    'Connecting to network port:\n': '连线到网络端口：\n',
    'Could not connect an Arduino\nNo boards found': '无法连接到Arduino\n找不到控制板',
    'Could not talk to Arduino in port\n': '无法与Arduino联系，端口：\n',
    'Disconnect Arduino': '断开与Arduino的连接',
    'Enter hostname or ip address:': '输入主机名或IP地址：',
    'Error connecting the board.': '连接控制板时发生错误',
    'It seems that someone pulled the cable!': '看来有人拔掉连接线了！',
    'Network port': '网络端口  ',
    'Network serial ports': '网络串口',
    'New Arduino translatable project': '新增Arduino可转译项目',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': '已经有一个控制板连接到这个角色了',
    'This may take a few seconds...': '可能要等数秒…',
    'analog reading _': '模拟输入值 _',
    'angle (0-180)': '角度 (0-180)',
    'clockwise (1500-1000)': '顺时针 (1500-1000)',
    'clockwise': '顺时针',
    'connect arduino at _': '连接位于 _ 的Arduino板',
    'connect to Arduino': '连接到Arduino板',
    'counter-clockwise (1500-2000)': '逆时针 (1500-2000)',
    'counter-clockwise': '逆时针',
    'digital input': '数字输入',
    'digital output': '数字输出',
    'digital reading _': '数字输入值 _',
    'disconnect Arduino': '断开与Arduino的连接',
    'disconnect arduino': '断开与Arduino的连接',
    'disconnected': '断开连接',
    'select a port': '选择一个端口',
    'servo': '舵机',
    'set digital pin _ to _': '数字脚 _ 设置成 _',
    'set pin _ to value _': '_ 脚的值设置成 _',
    'set servo _ to _': '_ 脚的舵机设置成 _',
    'setup digital pin _ as _': '数字脚 _ 设置成 _',
    'stopped (1500)': '停止 (1500)',
    'stopped': '停止'
};
// Add attributes to original SnapTranslator.dict.zh_CN
for (var attrname in s4aTempDict) { SnapTranslator.dict.zh_CN[attrname] = s4aTempDict[attrname]; }
