s4aTempDict = {
    'About Snap4Arduino...': 'Sobre Snap4Arduino...',
    'Adding extra features to StandardFirmata: tone, pulseIn, pulseOut, ping, nunchuck and dht11 blocks. It requires SA5Firmata_tone firmware.': 'Afegeix funcionalitats al StandardFirmata: tone, pulseIn, pulseOut, ping, nunchuck i dht11. Requereix que el dispositiu tingui el firmware SA5Firmata_tone.',
    'An Arduino board has been connected. Happy prototyping!': 'S\'ha connectat correctament una placa Arduino.\nFeliç prototipatge!',
    'An error was detected on the board\n\n': 'S\'ha detectat un error a la placa\n\n',
    'Blocks for the Echidna boards. Use StandarFirmata or SA5Firmata_tone to add more buzzer features.': 'Blocs per les plaques Echidna. Utilitza el StandardFirmata o el SA5Firmata_tone per afegir les funcionalitats del brunzidor (tone).',
    'Blocks for the Imagina shield. Use StandardFirmata, SA5Firmata_tone to add buzzer features or SA5Firmata_IR for buzzer and IR features.': 'Blocs per la placa Imagina. Utilitza el StandardFirmata, el S5AFirmata_tone per afegir les funcionalitats del brunzidor (tone) o el SA5Firmata_IR per tenir brunzidor (simplificat) i funcionalitats IR.',
    'Blocks for the NodeMCU board using StandardFirmata. It has also blocks for a motor shield.': 'Blocs per la placa NodeMCU utilitzant el StandardFirmata. També incorpora blocs per la placa de motors.',
    'Blocks for the TdRSTEAM shield v1. Use StandardFirmata or SA5Firmata_tone firmware to add buzzer features.': 'Blocs per la TdRSTEAM v1. Utilitza el StandardFirmata o el SA5Firmata_tone per afegir les funcionalitas del brunzidor (tone).',
    'Blocks for the TdRSTEAM shield v2, Use StandardFirmata or SA5Firmata_tone firmware to add buzzer features.': 'Blocs per la TdRSTEAM v2. Utilitza el StandardFirmata o el SA5Firmata_tone per afegir les funcionalitas del brunzidor (tone).',
    'Board is not connected': 'La placa no està connectada',
    'Board was disconnected from port\n': 'S\'ha desconnectat la placa del port\n',
    'Check if firmata is loaded.': 'Reviseu que Firmata hi estigui carregat.',
    'Connect Arduino': 'Connecta Arduino',
    'Connecting board at port\n': 'Connectant placa al port\n',
    'Connecting to network port:\n': 'Connectant a port de xarxa:\n',
    'Could not connect an Arduino\nNo boards found': 'No s\'ha pogut connectar cap Arduino\nNo s\'ha trobat cap placa',
    'Could not talk to Arduino in port\n': 'No s\'ha pogut establir comunicació amb Arduino al port\n',
    'Disconnect Arduino': 'Desconnecta Arduino',
    'Echidna Boards': 'Plaques Echidna',
    'Enter hostname or ip address:': 'Introdueix el nom de l\'host o adreça IP',
    'Error connecting the board.': 'Error en connectar a la placa',
    'Extra blocks for SnapJunior.': 'Blocs per afegir funcionalitats a l\'Snap Junior',
    'HTTP server': 'Servidor HTTP',
    'I2C': 'I2C',
    'Icon-based blocks for the youngest programmers.': 'Blocs amb icones per als programadors i programadores més joves.',
    'Imagina Shield': 'Placa Imagina',
    'It seems that someone pulled the cable!': 'Sembla que algú ha desconnectat el cable!',
    'Libraries below this point are specific to Snap4Arduino.': 'Les llibreries de sota són específiques per Snap4Arduino.',
    'Loading Snap Jr.': 'S\'està carregant Snap Júnior',
    'More supported devices': 'Altres dispositus compatibles',
    'Network port': 'Port de xarxa',
    'Network serial ports': 'Ports sèrie sobre xarxa',
    'New Arduino translatable project': 'Nou projecte traduïble a Arduino',
    'Open from URL...': 'Obre des d\'una URL...',
    'PWM': 'PWM',
    'Public stage': 'Escenari públic',
    'SA5Firmata with IR features at the expense of simplifying the tone function. It requires SA5Firmata_ir firmware.': 'SA5Firmata amb funcionalitats IR, limitant les funcionalitats del tone. Requereix que el dispositiu tingui el firmware SA5Firmata_IR.',
    'Save, share and get URL...': 'Desa, comparteix i mostra la URL...',
    'Scale a value from a range to another. Useful to map sensor values into stage coordinates, or to map sensors into actuators.': 'Escala un valor d\'un interval a un altre. Útil per mapejar els valors dels sensors a les coordenades de l\'escenari o per passar valors dels sensors directament als actuadors.',
    'Scale between ranges': 'Escala entre intervals',
    'Send and receive data from I2C-enabled sensors and actuators.': 'Envia i rep dades pel protocol I2C de sensors i actuadors.',
    'Show project URL': 'Mostra la URL del projecte',
    'Snap4Arduino connector required': 'Connector d\'Snap4Arduino requerit',
    'Snap4Arduino repository': 'Repositori de Snap4Arduino',
    'Snap4Arduino website': 'Web de Snap4Arduino',
    'SnapJunior Blocks': 'Blocs de l\'Snap Junior',
    'SnapJuniorPlus Blocks': 'Més blocs per l\'Snap Junior',
    'Start Snap4Arduino in an\nicon-based blocks mode\nfor the youngest programmers': 'Inicia Snap4Arduino en un\nmode de blocs amb icones\nper els/les programadors/es més joves',
    'Start a Snap Jr. session': 'Inicia una sessió de Snap Júnior',
    'There is already a board connected to this sprite': 'Aquest objecte ja té una placa connectada',
    'This may take a few seconds...': 'Aquesta operació pot trigar uns segons...',
    'This project is now public at the following URL:': 'Aquest projecte és públic, accessible des de la URL:',
    'Upload firmware on UNO boards': 'Actualitza el firmware de plaques UNO',
    'analog reading  _': 'lectura analògica  _',
    'angle (0-180)': 'angle (0-180)',
    'arduino connected?': 'arduino connectat?',
    'blue': 'blau',
    'check to allow the stage\nto be viewed\nfrom the HTTP server': 'marqueu per permetre que l\'escenari\nes vegi des del servidor HTTP',
    'check to start\nHTTP server, allowing\nremote control\nof Snap4Arduino': 'marqueu per iniciar\nel servidor HTTP, permetent\nel control remot\nde Snap4Arduino',
    'clockwise (1500-1000)': 'sentit horari (1500-1000)',
    'clockwise': 'sentit horari',
    'connect arduino at  _': 'connecta l\'Arduino al port  _',
    'connect to Arduino': 'connecta a Arduino',
    'counter-clockwise (1500-2000)': 'sentit anti-horari (1500-2000)',
    'counter-clockwise': 'sentit anti-horari',
    'digital input': 'entrada digital',
    'digital output': 'sortida digital',
    'digital reading  _': 'lectura digital  _',
    'disconnect Arduino': 'desconnecta Arduino',
    'disconnect arduino': 'desconnecta l\'Arduino',
    'disconnected': 'desconnectat',
    'red': 'vermell',
    'select a port': 'selecciona un port',
    'servo': 'servo',
    'set digital pin  _ to  _': 'posa el pin digital  _ a  _',
    'set pin  _ to value  _': 'posa el pin  _ al valor  _',
    'set servo  _ to  _': 'posa el servo  _ a  _',
    'setup digital pin  _ as  _': 'configura pin  _ com a  _',
    'stopped (1500)': 'aturat (1500)',
    'stopped': 'aturat',
    'uncheck to prevent the stage\nfrom being viewed\nfrom the HTTP server': 'desmarqueu per evitar que l\'escenari\nes vegi des del servidor HTTP',
    'uncheck to stop\nHTTP server': 'desmarqueu per aturar\nel servidor HTTP'
};
// Add attributes to original SnapTranslator.dict.ca
for (var attrname in s4aTempDict) { SnapTranslator.dict.ca[attrname] = s4aTempDict[attrname]; }
