s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Ein Arduino-Board wurde verbunden. Fröhliches Prototyping!',
    'An error was detected on the board\n\n': 'Es wurde ein Fehler auf dem Board festgestellt\n\n',
    'Board is not connected': 'Board ist nicht verbunden',
    'Board was disconnected from port\n': 'Verbindung zum Board wurde getrennt an Port\n',
    'Check if firmata is loaded.': 'Überprüfe, ob die Firmata geladen wurde.',
    'Connect Arduino': 'Mit Arduino verbinden',
    'Connecting board at port\n':  'Verbinde mit Board an Port\n',
    'Could not connect an Arduino\nNo boards found': 'Konnte nicht mit Arduino verbinden\nKeine Boards gefunden',
    'Could not talk to Arduino in port\n': 'Kommunikation mit Arduino fehlgeschlagen an Port\n',
    'Disconnect Arduino': 'Verbindung zu Arduino trennen',
    'Error connecting the board.': 'Fehler beim verbinden mit dem Board.',
    'It seems that someone pulled the cable!': 'Scheinbar hat jemand das Kabel gezogen!',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Es ist bereits ein Board mit diesem Sprite verbunden',
    'analog reading _': 'lies analogen Pin _',
    'angle (0-180)': 'Winkel (0-180)',
    'clockwise (1500-1000)': 'im Uhrzeigersinn (1500-1000)',
    'clockwise': 'im Uhrzeigersinn',
    'connect arduino at _': 'verbinde Arduino an Port _',
    'connect to Arduino': 'mit Arduino verbinden',
    'counter-clockwise (1500-2000)': 'gegen den Uhrzeigersinn (1500-2000)',
    'counter-clockwise': 'gegen den Uhrzeigersinn',
    'digital input': 'digitaler Eingang',
    'digital output': 'digitaler Ausgang',
    'digital reading _': 'lies digitalen Pin _',
    'disconnect Arduino': 'Verbindung zu Arduino trennen',
    'disconnect arduino': 'verbindung zu Arduino trennen',
    'servo': 'Servo',
    'set digital pin _ to _': 'Setze digitalen Pin _ auf _',
    'set pin _ to value _': 'Setze Pin _ auf _',
    'set servo _ to _': 'Setze Servo _ auf _',
    'setup digital pin _ as _': 'Einrichten des digitalen Pins _ als _',
    'stopped (1500)': 'gestoppt (1500)',
    'stopped': 'gestoppt'
};
// Add attributes to original SnapTranslator.dict.de
for (var attrname in s4aTempDict) { SnapTranslator.dict.de[attrname] = s4aTempDict[attrname]; }
