s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Een Arduino is verbonden. Veel prototyping-plezier!',
    'An error was detected on the board\n\n': 'Er is een fout opgetreden in de Arduino\n\n',
    'Board is not connected': 'Arduino is niet verbonden',
    'Board was disconnected from port\n': 'De verbinding is verbroken op poort\n',
    'Check if firmata is loaded.': 'Controleer of Firmata is geladen.',
    'Connect Arduino': 'verbinding maken',
    'Connecting board at port\n': 'Verbinding maken op poort\n',
    'Could not connect an Arduino\nNo boards found': 'Het is niet gelukt om verbinding te maken met de Arduino\nEr is geen Arduino gevonden',
    'Could not talk to Arduino in port\n': 'Er is geen communicatie mogelijk op poort\n',
    'Disconnect Arduino': 'verbinding verbreken',
    'Error connecting the board.': 'Fout bij het maken van de verbinding.',
    'It seems that someone pulled the cable!': 'Blijkbaar heeft iemand de kabel eruit getrokken!',
    'New Arduino translatable project': 'Nieuw Arduino-project maken',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Er is al een verbinding voor deze sprite',
    'analog reading _': 'lees analoge pin _ uit',
    'angle (0-180)': 'hoek (0-180)',
    'clockwise (1500-1000)': 'rechtsom (1500-1000)',
    'clockwise': 'rechtsom',
    'connect arduino at _': 'verbind Arduino met _',
    'connect to Arduino': 'maak verbinding met Arduino',
    'counter-clockwise (1500-2000)': 'linksom (1500-2000)',
    'counter-clockwise': 'linksom',
    'digital input': 'digitale ingang',
    'digital output': 'digitale uitgang',
    'digital reading _': 'lees digitale pin _ uit',
    'disconnect Arduino': 'verbreek verbinding met Arduino',
    'disconnect arduino': 'verbinding verbreken',
    'servo': 'servo',
    'set digital pin _ to _': 'zet digitale pin _ op _',
    'set pin _ to value _': 'zet pin _ op _',
    'set servo _ to _': 'zet servo _ op _',
    'setup digital pin _ as _': 'stel digitale pin _ in als _',
    'stopped (1500)': 'gestopt (1500)',
    'stopped': 'gestopt'
};
// Add attributes to original SnapTranslator.dict.nl
for (var attrname in s4aTempDict) { SnapTranslator.dict.nl[attrname] = s4aTempDict[attrname]; }
