s4aTempDict = {
    'An Arduino board has been connected. Happy prototyping!': 'Ett Arduino kort har anslutits. Skapa n\u00e5got trevligt.',
    'An error was detected on the board\n\n': 'Ett fel har uppt\u00e4ckts på arduino kortet\n\n',
    'Are you sure you want to leave?': '\u00C4r du s\u00E4ker du vill avsluta?',
    'Board is not connected': 'Arduino \u00e4r inte ansluten',
    'Board was disconnected from port\n': 'Ett Arduino kort har fr\u00e5nkopplats fr\u00e5n port\n',
    'Check if firmata is loaded.': 'Kontrollera att firmata \u00e4r installerad.',
    'Connect Arduino': 'Anslut Arduino',
    'Connecting board at port\n': 'Ansluter arduino till port\n',
    'Connecting to network port:\n': 'Ansluter till n\u00e4tverksport:\n',
    'Could not connect an Arduino\nNo boards found': 'Kunde inte ansluta\nInga Arduino kort hittades',
    'Could not talk to Arduino in port\n': 'Kan inte kommunicera med Arduino på port\n',
    'Disconnect Arduino': 'Fr\u00e5koppla Arduino',
    'Enter hostname or ip address:': 'Ange v\u00e4rdnamn eller ip-adress:',
    'Error connecting the board.': 'Ett fel uppstod n\u00e4r Arduino kortet skulle anslutas.',
    'It seems that someone pulled the cable!': 'Det ser ut som att n\u00e5gon drog ur kabeln!',
    'Network port': 'N\u00e4tverksport',
    'Network serial ports': 'N\u00e4tverksserieportar',
    'New Arduino translatable project': 'Nytt \u00f6vers\u00e4ttningsbart Arduino projekt',
    'PWM': 'PWM',
    'There is already a board connected to this sprite': 'Ett Arduino kort \u00e4r redan anslutet till denna sprite',
    'This may take a few seconds...': 'Det kan ta n\u00e5gra sekunder...',
    'analog reading _': 'analog avl\u00e4sning _',
    'angle (0-180)': 'vinkel (0-180)',
    'clockwise (1500-1000)': 'medsols (1500-1000)',
    'clockwise': 'medsols',
    'connect arduino at _': 'anslut arduino till _',
    'connect to Arduino': 'anslut Arduino',
    'counter-clockwise (1500-2000)': 'motsols (1500-2000)',
    'counter-clockwise': 'motsols',
    'digital input': 'Digital ing\u00e5ng',
    'digital output': 'Digital utg\u00e5ng',
    'digital reading _': 'digital avl\u00e4sning _',
    'disconnect Arduino': 'fr\u00e5koppla Arduino',
    'disconnect arduino': 'fr\u00e5koppla arduino',
    'disconnected': 'fr\u00e5nkopplad',
    'select a port': 'v\u00e4lj en port',
    'servo': 'servo',
    'set digital pin _ to _': 's\u00e4tt digital pin _ till _',
    'set pin _ to value _': 's\u00e4tt pin _ till v\u00e4rde _',
    'set servo _ to _': 's\u00e4tt servo _ till _',
    'setup digital pin _ as _': 'konfigurera digital pin _ som _',
    'stopped (1500)': 'stoppad (1500)',
    'stopped': 'stoppad'
};
// Add attributes to original SnapTranslator.dict.sv
for (var attrname in s4aTempDict) { SnapTranslator.dict.sv[attrname] = s4aTempDict[attrname]; }
